name = "careermatch-capstone"
main = ".output/server/index.mjs"
compatibility_date = "2026-05-16"
compatibility_flags = ["nodejs_compat"]
account_id = "82a6a4e89ea2c4f761add823c23abcfc"
no_bundle = true

[assets]
binding = "ASSETS"
directory = ".output/public"

[[rules]]
type = "ESModule"
globs = ["**/*.mjs", "**/*.js"]

[[kv_namespaces]]
binding = "CAREERMATCH_KV"
id = "68e2a0205f9e4282a5f94c5d325f60db"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "84327efcc1894753b541d5d79eba2953"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1

[vars]
N8N_WEBHOOK_URL = "https://syahrul123.app.n8n.cloud/webhook/ai-job-matching"
CHATBOT_URL = "https://syahrul123.app.n8n.cloud/webhook/interview-chat-trigger-001/chat"
BETTER_AUTH_URL = "https://careermatch-capstone.xfhreall.workers.dev"
BETTER_AUTH_SECRET = "this-fucking-secret-auth-password-pass-ahahaha"
GOOGLE_CLIENT_ID = "827234044893-okhdspe4l36sgrshgs3i6l4ckvh0fbln.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
DATABASE_URL = "postgresql://postgres.ldqlacetcemhwyqzgnum:xfhreall377@aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres"
SUPABASE_URL = "https://ldqlacetcemhwyqzgnum.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkcWxhY2V0Y2VtaHd5cXpnbnVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1OTMzNTIsImV4cCI6MjA4NzE2OTM1Mn0.Q8sAwbEey8DD2yXoXWlHN4fzfuX-QNRMRCJdhYE077w"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkcWxhY2V0Y2VtaHd5cXpnbnVtIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MTU5MzM1MiwiZXhwIjoyMDg3MTY5MzUyfQ._hVanwvRVVvv-UgpvAMmGD8fNWkB8wRMEyixuYB6VV8"
SUPABASE_DB_PASSWORD = "xfhreall377"
